Repository SuimKim/medi-click, pull requests merged in 2025-03, with the labels that each got.

#5 [Setting] 카카오 지도 sdk 라이브러리 설치
  package.json
  pnpm-lock.yaml
Labels: ⚙ Setting, 🐣 민조

#11 [Feature]#3 공통 레이아웃 - header 제작
  .eslintrc.json
  src/app/(reservation)/hospital/page.tsx
  src/app/layout.tsx
  src/components/layout/Header.tsx
  src/components/layout/Nav.tsx
  src/components/ui/button.tsx
  src/constants/routerPath.ts
Labels: ✨ Feature, 🎨 HTML&CSS, 🐣 민조

#12 [Feature]#1 예약 페이지 기본 레이아웃 생성
  src/app/(reservation)/reserve/.gitkeep
  src/app/(reservation)/reserve/page.tsx
  src/app/layout.tsx
  src/components/features/.gitkeep
  src/components/features/reserve/CalendarCard.tsx
  src/components/features/reserve/FormCard.tsx
  src/components/features/reserve/ReserveTimeCard.tsx
  src/components/layout/.gitkeep
  src/components/layout/CardContainer.tsx
Labels: ✨ Feature, 🎨 HTML&CSS, 🍔 지은

#18 [Style]#4 병원 상세 페이지 및 관련 컴포넌트 추가
  src/app/(reservation)/hospital/[...id]/.gitkeep
  src/app/(reservation)/hospital/[...id]/page.tsx
  src/components/features/hospitalDetail/HospitalBasicInfo.tsx
  src/components/features/hospitalDetail/InfoSection.tsx
  src/components/features/hospitalDetail/ProgressBar.tsx
  src/components/features/hospitalDetail/ReviewSection.tsx
  src/utils/func/calculatePercentage.ts
Labels: 🎨 HTML&CSS, 🐶 수민

#19 [Style]#7 메인 홈페이지 레이아웃 제작
  src/app/page.tsx
  src/components/common/HospitalCard.tsx
  src/components/features/home/Banner.tsx
  src/components/features/home/HospitalList.tsx
  src/components/features/home/KaKaoMap.tsx
  src/components/features/home/SearchBar.tsx
  src/components/ui/button.tsx
  src/components/ui/input.tsx
Labels: 🎨 HTML&CSS, 🐣 민조

#21 [Feature]#17 예약 페이지 레이아웃 생성
  package.json
  pnpm-lock.yaml
  src/app/(reservation)/reserve/[...id]/page.tsx
  src/app/(reservation)/reserve/page.tsx
  src/components/features/reserve/CalendarCard.tsx
  src/components/features/reserve/CalendarFunnel.tsx
  src/components/features/reserve/FormCard.tsx
  src/components/features/reserve/FormFunnel.tsx
  src/components/features/reserve/ReserveTimeCard.tsx
  src/components/features/reserve/TimeFunnel.tsx
  src/components/layout/CardContainer.tsx
  src/types/context.ts
Labels: ✨ Feature, 🎨 HTML&CSS, 🍔 지은

#25 [Feature]#22 예약 페이지 - 날짜 선택 페이지 생성
  package.json
  pnpm-lock.yaml
  src/app/(reservation)/reserve/[...id]/page.tsx
  src/app/layout.tsx
  src/components/features/reserve/CalendarFunnel.tsx
  src/components/features/reserve/TimeFunnel.tsx
  src/components/layout/CardContainer.tsx
  src/components/ui/calendar.tsx
  src/types/.gitkeep
  src/utils/func/.gitkeep
  src/utils/func/getCalendarDate.ts
Labels: ✨ Feature, 🔨 Refactor, 🍔 지은

#31 [Feature]#2 병원 상세 정보 페이지 기본 정보 섹션 구현
  src/app/(reservation)/hospital/[...id]/page.tsx
  src/app/api/.gitkeep
  src/app/api/hospitalDetail/route.ts
  src/app/layout.tsx
  src/components/features/hospitalDetail/HospitalBasicInfo.tsx
  src/components/features/hospitalDetail/HospitalSection.tsx
  src/components/features/hospitalDetail/ProgressBar.tsx
  src/constants/apiUrl.ts
  src/constants/queryKey.ts
  src/provider/.gitkeep
  src/provider/TQProvider.tsx
  src/utils/api/hospitalDetail.ts
  src/utils/func/calculatePercentage.ts
  src/utils/func/convertToTimeFormat.ts
  src/utils/func/formatTelephoneNumber.ts
Labels: ✨ Feature, 🐶 수민

#36 [Style]#32 my page 예약 상세보기 레이아웃
  src/app/(auth)/mypage/page.tsx
  src/components/features/mypage/MyReserveDetail/Banner/Banner.tsx
  src/components/features/mypage/MyReserveDetail/Banner/BannerContainer.tsx
  src/components/features/mypage/MyReserveDetail/MyReserveDetail.tsx
  src/components/features/mypage/MyReserveDetail/ReserveContents/ContentsContainer.tsx
  src/components/features/mypage/MyReserveDetail/ReserveContents/InfoContainer.tsx
  src/components/features/mypage/MyReserveDetail/ReserveContents/InfoDetailContainer.tsx
  src/components/features/mypage/MyReserveDetail/ReserveContents/InfoDetailContents.tsx
  src/components/features/mypage/MyReserveDetail/ReserveContents/InfoMap.tsx
  src/components/features/mypage/MyReserveDetail/ReserveContents/InfoTitleBox.tsx
  src/components/features/mypage/MyReserveDetail/ReserveContents/ReserveContents.tsx
Labels: ✨ Feature, 🎨 HTML&CSS, 🍀 수임

#42 [Feat]#2 병원 상세 정보 및 정보 섹션 조회 기능 추가 및 레이아웃 개선
  src/app/layout.tsx
  src/components/features/hospitalDetail/HospitalBasicInfo.tsx
  src/components/features/hospitalDetail/HospitalSection.tsx
  src/constants/queryKey.ts
  src/utils/api/hospitalDetail.ts
Labels: ✨ Feature, 🐶 수민

#40 [Style]#39 my page 개인 정보 수정
  src/app/(auth)/mypage/page.tsx
  src/components/features/mypage/editProfile/EditFormInput.tsx
  src/components/features/mypage/editProfile/EditProfile.tsx
  src/components/features/mypage/myReserveCalendar/MyReserveCalendar.tsx
  src/components/features/mypage/myReserveCalendar/myCalendar/MyCalendar.tsx
  src/components/features/mypage/myReserveCalendar/scheduleBox/ScheduleBox.tsx
  src/components/features/mypage/myReserveCalendar/scheduleBox/ScheduleContainer.tsx
  src/components/features/mypage/myReserveCalendar/scheduleBox/ScheduleTitleBox.tsx
  src/components/features/mypage/myReserveDetail/MyReserveDetail.tsx
  src/components/features/mypage/myReserveDetail/banner/Banner.tsx
  src/components/features/mypage/myReserveDetail/banner/BannerContainer.tsx
  src/components/features/mypage/myReserveDetail/reserveContents/ContentsContainer.tsx
  src/components/features/mypage/myReserveDetail/reserveContents/InfoContainer.tsx
  src/components/features/mypage/myReserveDetail/reserveContents/InfoDetailContainer.tsx
  src/components/features/mypage/myReserveDetail/reserveContents/InfoDetailContents.tsx
  src/components/features/mypage/myReserveDetail/reserveContents/InfoMap.tsx
  src/components/features/mypage/myReserveDetail/reserveContents/InfoTitleBox.tsx
  src/components/features/mypage/myReserveDetail/reserveContents/ReserveContents.tsx
  src/components/features/mypage/sideBar/ProfileImage.tsx
Labels: ✨ Feature, 🎨 HTML&CSS, 🍀 수임

#35 [Feature]#26 예약 페이지 - 폼 제출 페이지 기능 구현
  src/app/(reservation)/reserve/[...id]/page.tsx
  src/components/features/reserve/FormFunnel.tsx
  src/components/features/reserve/TimeFunnel.tsx
  src/constants/queryKey.ts
  src/hooks/map/useHospitalName.ts
  src/utils/api/hospitals.ts
  src/utils/func/getCalendarDate.ts
  tailwind.config.ts
Labels: 📬 API, ✨ Feature, 🎨 HTML&CSS, 🍔 지은

#45 [Feature]#33 예약 페이지 - 시간 선택 기능 간단 구현
  src/components/features/reserve/TimeFunnel.tsx
  src/components/layout/TimeButtonContainer.tsx
  src/components/ui/button.tsx
  src/utils/func/getCalendarDate.ts
Labels: ✨ Feature, 🎨 HTML&CSS, 🍔 지은

#47 [Refactor]#43 my page 리팩토링
  package.json
  pnpm-lock.yaml
  src/app/(auth)/mypage/layout.tsx
  src/app/(auth)/mypage/page.tsx
  src/app/(auth)/mypage/profile/page.tsx
  src/app/(auth)/mypage/reservation/[...id]/page.tsx
  src/app/(auth)/mypage/reservations/page.tsx
  src/components/features/mypage/ProfileImage.tsx
  src/components/features/mypage/ScheduleDetail.tsx
  src/components/features/mypage/layout/MyPageContainer.tsx
  src/components/features/mypage/layout/MyPageContentsContainer.tsx
  src/components/features/mypage/layout/sideBar/ProfileContainer.tsx
  src/components/features/mypage/layout/sideBar/SideBar.tsx
  src/components/features/mypage/layout/sideBar/UserMenuItem.tsx
  src/components/features/mypage/myReserveCalendar/MyReserveCalendar.tsx
  src/components/features/mypage/myReserveCalendar/scheduleBox/ScheduleBox.tsx
  src/components/features/mypage/myReserveDetail/MyReserveDetail.tsx
  src/components/features/mypage/sideBar/ProfileImage.tsx
  src/components/features/mypage/sideBar/SideBar.tsx
  src/components/features/mypage/sideBar/SideNav.tsx
  src/components/ui/avatar.tsx
  src/constants/routerPath.ts
  src/types/components/ui/mypage.schedule.ts
Labels: ✨ Feature, 🔨 Refactor, 🍀 수임

#44 [Feature]#41 병원 상세 페이지 카카오 맵 추가
  src/components/common/KakaoStaticMap.tsx
  src/components/features/hospitalDetail/HospitalBasicInfo.tsx
  src/components/features/hospitalDetail/HospitalSection.tsx
  src/hooks/map/useDetailHospitalLocation.ts
  src/utils/api/hospitalDetail.ts
Labels: ✨ Feature, 🐶 수민

#48 [Feature]#34 예약 페이지 - 시간 선택 (Supabase 연동)
  src/app/(reservation)/reserve/[...id]/page.tsx
  src/components/features/reserve/CalendarFunnel.tsx
  src/components/features/reserve/FormFunnel.tsx
  src/components/features/reserve/TimeFunnel.tsx
  src/components/layout/CardHeaderContainer.tsx
  src/utils/api/hospitals.ts
  src/utils/func/generateTimeSlots.ts
  src/utils/func/getCalendarDate.ts
Labels: 📬 API, ✨ Feature, 🍔 지은

#51 [Feature]#28 메인 홈페이지 - 병원 목록 무한스크롤 적용
  .vscode/settings.json
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/HospitalCard.tsx
  src/components/features/home/Banner.tsx
  src/components/features/home/HospitalList.tsx
  src/components/features/home/KaKaoMap.tsx
  src/components/ui/Text.tsx
  src/components/ui/Title.tsx
  src/constants/queryKey.ts
  src/hooks/map/useAllHospitalLocation.ts
  src/hooks/tanstackQuery/useHospitalInView.ts
  src/hooks/tanstackQuery/useHospitalsInfiniteQuery.ts
  src/utils/api/hospitals.ts
Labels: ✨ Feature, 🎨 HTML&CSS, 🐣 민조

#53 [Feature]#46 병원상세 리뷰 조회 기능 추가
  src/components/features/hospitalDetail/HospitalSection.tsx
  src/components/features/hospitalDetail/ReviewSection.tsx
  src/constants/queryKey.ts
  src/constants/reviewConstants.ts
  src/utils/api/hospitalDetail.ts
  src/utils/func/getReviewKeywordCounts.ts
Labels: ✨ Feature, 🐶 수민

#55 Feature/#14,#16 로그인, 회원가입 로직 추가
  src/components/features/auth/AuthForm.tsx
  src/constants/authMode.ts
  src/utils/api/auth.ts
Labels: 📬 API, ✨ Feature, 🐿️ 현식

#60 [Refactor]#54 병원 상세 페이지 리펙토링
  src/app/(reservation)/hospital/[...id]/page.tsx
  src/components/features/hospitalDetail/ErrorState.tsx
  src/components/features/hospitalDetail/HospitalSection.tsx
  src/components/features/hospitalDetail/ReviewSection.tsx
  src/constants/hospitalConstants.ts
  src/hooks/hospitalDetail/useHospitalSchedule.ts
  src/hooks/tanstackQuery/useHospitalInfo.ts
  src/types/components/hospitalDetail/hospitalInfoData.ts
  src/utils/api/hospitalDetail.ts
  src/utils/func/getOfficeWeeks.ts
  src/utils/func/getReviewKeywordCounts.ts
Labels: 🔨 Refactor, 🐶 수민

#57 [Bugfix]#50 시간 선택 기능 관련 오류 해결
  src/app/(reservation)/reserve/[...id]/page.tsx
  src/components/features/reserve/CalendarFunnel.tsx
  src/components/features/reserve/FormFunnel.tsx
  src/components/features/reserve/TimeFunnel.tsx
  src/constants/StorageKey.ts
  src/types/context.ts
  src/utils/func/getLocalStorage.tsx
Labels: 🐞 BugFix, ✨ Feature, 🍔 지은

#61 [Feature]#52 메인 홈페이지 - 병원 검색 기능 구현
  .vscode/settings.json
  src/components/common/HospitalCard.tsx
  src/components/features/home/CustomOverlay.tsx
  src/components/features/home/EventMarkerContainer.tsx
  src/components/features/home/HospitalList.tsx
  src/components/features/home/KaKaoMap.tsx
  src/components/features/home/SearchBar.tsx
  src/hooks/map/useCurrentLocation.ts
  src/hooks/tanstackQuery/useHospitalsInfiniteQuery.ts
  src/types/map.ts
  src/utils/api/hospitals.ts
  src/utils/func/checkEmptyPages.ts
  src/utils/zustand/useHospitalStore.ts
  src/utils/zustand/useSearchStore.ts
Labels: ✨ Feature, 🐣 민조

#63 [Feature]#58 예약 페이지 제출 기능
  src/app/(reservation)/reserve/[id]/page.tsx
  src/components/features/reserve/FormFunnel.tsx
  src/components/features/reserve/TimeFunnel.tsx
  src/types/supabase.d.ts
  src/utils/api/reservation.ts
Labels: 📬 API, ✨ Feature, 🍔 지은

#62 [Featuer]#49 회원 정보 수정
  src/app/(auth)/mypage/layout.tsx
  src/app/(auth)/mypage/profile/page.tsx
  src/app/layout.tsx
  src/components/features/mypage/MainContentsTitleBox.tsx
  src/components/features/mypage/ProfileImage.tsx
  src/components/features/mypage/editProfile/EditFormInput.tsx
  src/components/features/mypage/editProfile/EditProfileForm.tsx
  src/components/features/mypage/layout/sideBar/SideBar.tsx
  src/components/features/mypage/myReserveDetail/reserveContents/InfoMap.tsx
  src/components/features/mypage/myReserveDetail/reserveContents/InfoTitleBox.tsx
  src/constants/queryKey.ts
  src/constants/supabaseTables.ts
  src/hooks/tanstackQuery/useUpdateProfile.ts
  src/hooks/tanstackQuery/useUserProfile.ts
  src/types/supabase.d.ts
  src/utils/api/userProfile.ts
  src/utils/func/validatePhoneNumber.ts
Labels: 📬 API, ✨ Feature, 🍀 수임

#71 [Bugfix]#64 debounce에 useCallback이 적용되지 않는 문제 해결 완료
  package.json
  pnpm-lock.yaml
  src/components/features/home/SearchBar.tsx
Labels: 🐞 BugFix, 🐣 민조

#70 [Feature]#67 내 예약 목록 가져오기
  src/app/(auth)/mypage/reservations/page.tsx
  src/components/features/mypage/MainContentsContainer.tsx
  src/components/features/mypage/MainContentsTitleBox.tsx
  src/components/features/mypage/ProfileImage.tsx
  src/components/features/mypage/ScheduleDetail.tsx
  src/components/features/mypage/editProfile/EditProfileForm.tsx
  src/components/features/mypage/layout/sideBar/SideBar.tsx
  src/components/features/mypage/myReservations/ReservationList.tsx
  src/components/features/mypage/myReserveCalendar/scheduleBox/ScheduleBox.tsx
  src/components/features/mypage/myReserveCalendar/scheduleBox/ScheduleTitleBox.tsx
  src/components/ui/Title.tsx
  src/constants/queryKey.ts
  src/constants/supabaseTables.ts
  src/hooks/tanstackQuery/useMyPageDataQuery.ts
  src/hooks/tanstackQuery/useUpdateProfileMutate.ts
  src/hooks/tanstackQuery/useUserProfile.ts
  src/types/components/ui/.gitkeep
  src/types/components/ui/mypage.schedule.ts
  src/types/supabase.d.ts
  src/utils/api/reservation.ts
  src/utils/api/userProfile.ts
Labels: 📬 API, ✨ Feature, 🍀 수임

#72 [Style]#59 예약 페이지 스타일 정리
  src/app/(reservation)/reserve/[id]/page.tsx
  src/components/features/reserve/CalendarFunnel.tsx
  src/components/features/reserve/FormFunnel.tsx
  src/components/features/reserve/TimeFunnel.tsx
  src/components/layout/CardContainer.tsx
  src/components/layout/TimeButtonContainer.tsx
  src/components/ui/Text.tsx
  src/components/ui/Title.tsx
  src/components/ui/button.tsx
  src/types/context.ts
Labels: 🎨 HTML&CSS, 🍔 지은

#75 [Feature]#74 og메타데이터 추가
  src/app/(reservation)/hospital/[...id]/page.tsx
Labels: ✨ Feature, 🐶 수민

#66 [Feature]#14,#16 회원가입 예외처리 추가
  src/components/features/auth/AuthForm.tsx
  src/components/ui/input.tsx
  src/utils/api/auth.ts
Labels: 📬 API, 🐞 BugFix, ✨ Feature, 🐿️ 현식

#78 [Feature]#76 병원 상세페이지 렌더링 방식 변경
  src/app/(reservation)/hospital/[...id]/page.tsx
  src/app/api/hospitalDetail/route.ts
  src/components/features/hospitalDetail/HospitalBasicInfo.tsx
  src/components/features/hospitalDetail/HospitalSection.tsx
  src/components/features/hospitalDetail/InfoSection.tsx
  src/components/features/hospitalDetail/MedicalHours.tsx
  src/components/features/hospitalDetail/ReviewSection.tsx
  src/hooks/hospitalDetail/useHospitalSchedule.ts
  src/hooks/map/useDetailHospitalLocation.ts
  src/hooks/tanstackQuery/useHospitalInfo.ts
  src/types/components/hospitalDetail/hospitalInfoData.ts
  src/utils/api/hospitalDetail.ts
Labels: ✨ Feature, 🔨 Refactor, 🐶 수민

#79 [Feature]#73 로그인 상태 관리하는 middleware 추가
  package.json
  pnpm-lock.yaml
  src/app/middleware.ts
  src/components/features/reserve/TimeFunnel.tsx
  src/utils/api/auth.ts
  src/utils/api/hospitalDetail.ts
  src/utils/api/hospitals.ts
  src/utils/api/reservation.ts
  src/utils/api/userProfile.ts
  src/utils/supabase/middleware.ts
  src/utils/supabase/supabase.ts
  src/utils/supabase/supabaseClient.ts
  src/utils/supabase/supabaseServer.ts
Labels: ✨ Feature, ⚙ Setting, 🐣 민조

#84 [Style]#77 마이페이지-병원측 환자 예약 목록 UI 마크업
  src/app/(auth)/mypage/reservations/page.tsx
  src/components/features/mypage/hospitalReservations/DateNavigation.tsx
  src/components/features/mypage/hospitalReservations/ReservationBanner.tsx
  src/components/features/mypage/hospitalReservations/ReservationTable.tsx
  src/components/features/mypage/hospitalReservations/Reservations.tsx
  src/components/features/mypage/hospitalReservations/StatusBadge.tsx
  src/constants/styles.ts
  src/utils/func/formatDate.ts
Labels: 🎨 HTML&CSS, 🐶 수민

#81 [Feature]#68 예약 중복 방지 기능 추가
  .eslintrc.json
  src/app/(reservation)/reserve/[id]/page.tsx
  src/components/features/reserve/FormFunnel.tsx
  src/components/features/reserve/NoReservationPage.tsx
  src/components/features/reserve/TimeFunnel.tsx
  src/components/layout/CardContainer.tsx
  src/hooks/reservation/useHospitalName.ts
  src/hooks/reservation/useReservationTime.ts
  src/hooks/tanstackQuery/useReservationDate.ts
  src/types/supabase.d.ts
  src/utils/api/reservation.ts
  src/utils/func/convertToTimeFormat.ts
  src/utils/func/getCalendarDate.ts
Labels: 📬 API, ✨ Feature, 🍔 지은

#85 [Refactor]#65 메인 홈페이지 - 리팩토링 및 기타 기능 추가
  public/img/bannerImg.jpg
  src/app/(reservation)/hospital/page.tsx
  src/app/global-error.tsx
  src/app/page.tsx
  src/components/features/home/Banner.tsx
  src/components/features/home/HospitalCard.tsx
  src/components/features/home/HospitalList.tsx
  src/components/features/home/KaKaoMap.tsx
  src/components/features/home/SearchBar.tsx
  src/components/features/home/layout/BannerContainer.tsx
  src/components/features/home/layout/HomeContainer.tsx
  src/components/features/home/layout/HospitalCardContainer.tsx
  src/components/features/home/layout/HospitalListContainer.tsx
  src/components/features/home/layout/KakaoMapContainer.tsx
  src/components/features/home/layout/SearchBarContainer.tsx
  src/components/features/home/map/CurrentLocationButton.tsx
  src/components/features/home/map/CustomOverlay.tsx
  src/components/features/home/map/EventMarkerContainer.tsx
  src/components/features/home/map/ZoomButton.tsx
  src/components/layout/Nav.tsx
  src/hooks/map/useCurrentLocation.ts
  src/hooks/map/useMapZoom.ts
  src/types/children.ts
  src/types/supabase.d.ts
Labels: 🔨 Refactor, 🐣 민조

#87 [Feature]/#56,#80 로그아웃 기능 추가 및 로그인 전역 상태 관리 기능 추가
  src/components/features/auth/AuthBox.tsx
  src/components/features/auth/AuthForm.tsx
  src/components/layout/Nav.tsx
  src/utils/api/auth.ts
  src/utils/api/authState.ts
  src/utils/zustand/useAuthStore.ts
Labels: 📬 API, ✨ Feature, ⚙ Setting, 🐿️ 현식

#82 [Feature]#69 예약 상세보기
  src/app/(auth)/mypage/page.tsx
  src/app/(auth)/mypage/reservation/[...id]/page.tsx
  src/components/features/mypage/ScheduleDetail.tsx
  src/components/features/mypage/myReservations/ReservationList.tsx
  src/components/features/mypage/myReserveCalendar/scheduleBox/ScheduleBox.tsx
  src/components/features/mypage/myReserveDetail/banner/Banner.tsx
  src/components/features/mypage/myReserveDetail/reserveContents/InfoDetailContents.tsx
  src/components/features/mypage/myReserveDetail/reserveContents/InfoMap.tsx
  src/components/features/mypage/myReserveDetail/reserveContents/ReserveContents.tsx
  src/components/ui/Text.tsx
  src/constants/queryKey.ts
  src/constants/reservationStatus.ts
  src/types/components/mypage/reservation.type.ts
  src/utils/api/reservation.ts
  src/utils/api/userProfile.ts
  src/utils/func/isPastDateTime.ts
  src/utils/func/validatePhoneNumber.ts
Labels: 📬 API, ✨ Feature, 🔨 Refactor, 🍀 수임

#95 [Feature]#89 로그인 상태에 따라 페이지 접근 및 회원가입 로직 수정
  src/app/(auth)/login/page.tsx
  src/app/(auth)/mypage/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(reservation)/reserve/[id]/page.tsx
  src/components/features/auth/AuthForm.tsx
  src/components/layout/Nav.tsx
  src/utils/access/protectedRouteClient.ts
  src/utils/access/protectedRouteServer.ts
  src/utils/api/auth.ts
Labels: ✨ Feature, 🐿️ 현식

#96 [Feature]#89 로그인 상태에 따라 페이지 접근 및 회원가입 로직 수정
  src/app/(auth)/login/page.tsx
  src/app/(auth)/mypage/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(reservation)/reserve/[id]/page.tsx
  src/components/features/auth/AuthForm.tsx
  src/components/layout/Nav.tsx
  src/utils/access/protectedRouteClient.ts
  src/utils/access/protectedRouteServer.ts
  src/utils/api/auth.ts
Labels: ✨ Feature, 🐿️ 현식

#100 [Feature]/#86 마이페이지 병원계정 예약된 환자 리스트 조회 및 확정 기능추가
  package.json
  pnpm-lock.yaml
  src/app/(auth)/mypage/reservations/page.client.tsx
  src/app/(auth)/mypage/reservations/page.tsx
  src/app/(reservation)/hospital/[...id]/page.tsx
  src/app/layout.tsx
  src/components/features/auth/AuthForm.tsx
  src/components/features/mypage/hospitalReservations/ReservationBanner.tsx
  src/components/features/mypage/hospitalReservations/ReservationTable.tsx
  src/components/features/mypage/hospitalReservations/Reservations.tsx
  src/components/features/mypage/hospitalReservations/StatusBadge.tsx
  src/components/features/mypage/layout/sideBar/SideBar.tsx
  src/components/features/mypage/myReserveCalendar/myCalendar/MyCalendar.tsx
  src/components/layout/Nav.tsx
  src/constants/queryKey.ts
  src/constants/styles.ts
  src/constants/supabaseTables.ts
  src/utils/api/hospitalReservationList.ts
  src/utils/func/formatDate.ts
  src/utils/func/isHospitalAccount.ts
  src/utils/zustand/useAccountStore.ts
Labels: ✨ Feature, 🐶 수민

#102 [Refactor]#101 로그인,회원가입 폼 리팩토링
  src/components/features/auth/AuthForm.tsx
  src/hooks/auth/useAuthFormHook.ts
Labels: 🔨 Refactor, 🐿️ 현식

#106 [Feature]#86 마이페이지 "대기중" 상태 배경색 미적용문제
  src/components/features/mypage/hospitalReservations/StatusBadge.tsx
  src/constants/styles.ts
Labels: 🎨 HTML&CSS, 🐶 수민
